### ISSUE TITLE
Enable RSS feed for the blog

### ISSUE THREAD

**Issue by elbaulp** [simplex-chat/website#24]
Great app!, just discovered and installed it. 

It would be great if you could enable a RSS feed for your blog, I would like to subscribe to keep up with the news.

Bests

**Comment by jnolan7599** [comment]
Very much agreed. I've add _https://github.com/simplex-chat/simplex-chat/releases.atom_ to my reader but it really doesn't do it the justice of the informative explanations found on the blog itself.

_Please_ add ASAP.

**Comment by yuuyins** [comment]
alternatives:
-  mastodon feed `https://mastodon.social/@simplex.rss`
- github feed: `https://github.com/simplex-chat/simplex-chat/releases.atom`
