### ISSUE TITLE
Scaling for the website is off on mobile.

### ISSUE THREAD

**Issue by vsevolod-mineev** [simplex-chat/website#3]
# This section of the website doesn't scale correctly on mobile:

![signal-2021-12-06-004910_001](https://user-images.githubusercontent.com/11165220/144771275-4d7ce631-44d7-4526-a313-19d0cce28b50.jpeg)
.

**Comment by shumvgolove** [comment]
Fixed with https://github.com/simplex-chat/website/commit/d5bcf37089cf2bf6385c3e5ebc26464b64e819e9
