### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by kamoii** [simplex-chat/website#7]
There is a broken link on the homepage.

![image](https://user-images.githubusercontent.com/52167401/152698044-4de4ae10-f06d-4f9d-a4b9-e8c5a6de594c.png)

**Comment by shumvgolove** [comment]
I think this already has been fixed, link goes to [this .md file](https://github.com/simplex-chat/simplexmq/blob/master/protocol/simplex-messaging.md).

**Comment by kamoii** [comment]
@shumvgolove 
Thanks. Confirmed it is fixed.
